import os
from dotenv import load_dotenv

load_dotenv() 

WEIGHTS = {
    "ai_project_depth": 40,
    "python_backend": 30,
    "cloud_fullstack": 15,
    "github": 10,
    "engineering_depth": 5,
}
assert sum(WEIGHTS.values()) == 100, "Weights must add up to 100"

#Eligibility

PYTHON_TERMS = [
    "python",
    "python 3",
    "python3",
    "cpython",
    "python scripting",
    "python programming",
    "python development",
    "python backend",
    "python automation",
    "python api",
    "python rest api",
    "python web development",
]

PYTHON_FRAMEWORKS = [
    "fastapi",
    "django",
    "flask",
    "pydantic",
    "pytest",
    "starlette",
    "tornado",
    "sanic",
    "aiohttp",
    "litestar",
    "falcon",
    "bottle",
    "streamlit",
    "gradio",
    "celery",
    "sqlalchemy",
    "alembic",
    "marshmallow",
]

AI_STRONG_TERMS = [
    "langchain",
    "langgraph",
    "llamaindex",
    "llama-index",
    "google adk",
    "agent development kit",
    "crewai",
    "autogen",
    "autogen framework",
    "semantic kernel",
    "haystack",
    "dspy",
    "rag",
    "retrieval-augmented generation",
    "retrieval augmented generation",
    "retrieval augmented",
    "retrieval pipeline",
    "retrieval system",
    "document retrieval",
    "semantic search",
    "hybrid search",
    "vector search",
    "vector database",
    "vector store",
    "vector db",
    "embeddings",
    "embedding model",
    "text embeddings",
    "sentence transformers",
    "sentence-transformers",
    "faiss",
    "chromadb",
    "chroma db",
    "pinecone",
    "weaviate",
    "milvus",
    "qdrant",
    "pgvector",
    "redis vector search",
    "opensearch",
    "elasticsearch vector search",
    "tool calling",
    "function calling",
    "structured output",
    "json mode",
    "multi-agent",
    "multi agent",
    "multi-agent system",
    "multi agent system",
    "agentic",
    "agentic ai",
    "agentic workflow",
    "ai agent",
    "ai agents",
    "autonomous agent",
    "autonomous agents",
    "llm",
    "llms",
    "large language model",
    "large language models",
    "generative ai",
    "generative artificial intelligence",
    "genai",
    "openai api",
    "openai",
    "gpt",
    "gpt-4",
    "gpt-4o",
    "gpt-4.1",
    "gpt-5",
    "gemini api",
    "gemini",
    "gemini model",
    "google gemini",
    "vertex ai",
    "anthropic api",
    "claude api",
    "claude",
    "mistral",
    "mistral ai",
    "llama",
    "llama 2",
    "llama 3",
    "llama 3.1",
    "llama 3.2",
    "llama 3.3",
    "hugging face",
    "huggingface",
    "transformers",
    "transformer models",
    "foundation model",
    "fine-tuning",
    "fine tuning",
    "instruction tuning",
    "prompt engineering",
    "prompt design",
    "few-shot learning",
    "zero-shot learning",
    "chain of thought",
    "reasoning model",
    "llm pipeline",
    "llm application",
    "llm applications",
    "llm orchestration",
    "llm workflow",
    "ai workflow",
    "agent workflow",
    "agent orchestration",
    "workflow orchestration",
    "memory",
    "conversation memory",
    "agent memory",
    "long-term memory",
    "short-term memory",
    "context retrieval",
    "context augmentation",
    "context window",
    "grounding",
    "grounded generation",
    "knowledge base",
    "knowledge graph",
    "document qa",
    "question answering",
    "qa system",
    "chatbot",
    "conversational ai",
    "text generation",
    "code generation",
    "summarization",
    "classification with llm",
    "llm evaluation",
    "rag evaluation",
    "agent evaluation",
    "guardrails",
    "llm guardrails",
    "ai safety",
    "content moderation",
    "hallucination detection",
    "hallucination mitigation",
    "prompt injection",
    "prompt injection detection",
    "model context protocol",
    "mcp",
]

AI_CLASSICAL_TERMS = [
    "scikit-learn",
    "sklearn",
    "tensorflow",
    "pytorch",
    "keras",
    "jax",
    "xgboost",
    "lightgbm",
    "catboost",
    "cnn",
    "convolutional neural network",
    "rnn",
    "recurrent neural network",
    "lstm",
    "gru",
    "transformer",
    "machine learning",
    "machine-learning",
    "deep learning",
    "deep-learning",
    "neural network",
    "neural networks",
    "artificial neural network",
    "ann",
    "computer vision",
    "opencv",
    "nlp",
    "natural language processing",
    "natural language understanding",
    "image classification",
    "image recognition",
    "object detection",
    "image segmentation",
    "semantic segmentation",
    "instance segmentation",
    "face detection",
    "face recognition",
    "feature extraction",
    "feature engineering",
    "transfer learning",
    "supervised learning",
    "unsupervised learning",
    "semi-supervised learning",
    "self-supervised learning",
    "reinforcement learning",
    "classification",
    "regression",
    "clustering",
    "random forest",
    "decision tree",
    "gradient boosting",
    "xgboost",
    "svm",
    "support vector machine",
    "logistic regression",
    "linear regression",
    "naive bayes",
    "k-means",
    "pca",
    "principal component analysis",
    "anomaly detection",
    "outlier detection",
    "recommendation system",
    "recommender system",
    "time series forecasting",
    "forecasting model",
    "sentiment analysis",
    "text classification",
    "named entity recognition",
    "ner",
    "speech recognition",
    "audio classification",
    "generative adversarial network",
    "gan",
    "gan architecture",
    "vae",
    "variational autoencoder",
    "autoencoder",
    "diffusion model",
    "stable diffusion",
    "yolo",
    "yolov5",
    "yolov8",
    "yolov9",
    "yolov10",
    "yolov11",
    "resnet",
    "efficientnet",
    "mobilenet",
    "vgg",
    "densenet",
    "inception",
    "bert",
    "roberta",
    "distilbert",
    "albert",
]

AI_VAGUE_TERMS = [
    "ai-powered",
    "ai powered",
    "ai-driven",
    "ai driven",
    "ai-based",
    "ai based",
    "ai-enabled",
    "ai enabled",
    "ai model",
    "ai models",
    "artificial intelligence",
    "artificially intelligent",
    "intelligent system",
    "intelligent systems",
    "smart system",
    "smart systems",
    "machine intelligence",
    "intelligent automation",
    "ai solution",
    "ai solutions",
    "ai application",
    "ai applications",
    "ai technology",
    "ai technologies",
    "ai platform",
    "ai platforms",
]

AI_TOOL_TERMS = [
    "copilot",
    "github copilot",
    "cursor",
    "chatgpt",
    "openai chatgpt",
    "claude",
    "anthropic claude",
    "gemini",
    "google gemini",
    "codeium",
    "windsurf",
    "tabnine",
    "amazon q",
    "amazon codewhisperer",
    "ai-assisted",
    "ai assisted",
    "ai-assisted coding",
    "ai assisted coding",
    "ai tools",
    "ai coding tools",
    "generative ai tools",
    "used ai to code",
    "used chatgpt",
    "used copilot",
    "used cursor",
    "prompted chatgpt",
    "prompt engineering for coding",
]

AI_PRODUCTION_TERMS = [
    "model deployment",
    "model serving",
    "inference pipeline",
    "inference server",
    "model api",
    "model endpoint",
    "mlops",
    "ml ops",
    "model monitoring",
    "model registry",
    "model versioning",
    "model optimization",
    "model quantization",
    "quantization",
    "distillation",
    "knowledge distillation",
    "onnx",
    "onnx runtime",
    "tensorflow serving",
    "torchserve",
    "triton inference server",
    "vllm",
    "ollama",
    "hugging face inference",
    "vertex ai deployment",
    "aws sagemaker",
    "azure machine learning",
    "mlflow",
    "weights and biases",
    "wandb",
]

AI_DATA_TERMS = [
    "training dataset",
    "training data",
    "validation dataset",
    "test dataset",
    "data preprocessing",
    "data augmentation",
    "data pipeline",
    "feature pipeline",
    "embedding pipeline",
    "document ingestion",
    "document chunking",
    "text chunking",
    "chunking strategy",
    "chunk overlap",
    "metadata filtering",
    "metadata extraction",
    "data labeling",
    "annotation",
    "synthetic data",
    "data cleaning",
    "data normalization",
    "tokenization",
    "tokenizer",
    "dataset curation",
]

AI_EVALUATION_TERMS = [
    "model evaluation",
    "model validation",
    "evaluation metrics",
    "precision",
    "recall",
    "f1 score",
    "f1-score",
    "accuracy",
    "auc",
    "roc auc",
    "confusion matrix",
    "bleu",
    "rouge",
    "bertscore",
    "perplexity",
    "retrieval evaluation",
    "retrieval metrics",
    "context relevance",
    "faithfulness",
    "answer relevance",
    "groundedness",
    "ragas",
    "deepeval",
    "benchmark",
    "benchmarking",
    "offline evaluation",
    "online evaluation",
]

AI_INFRASTRUCTURE_TERMS = [
    "gpu",
    "cuda",
    "cuda toolkit",
    "cudnn",
    "distributed training",
    "model parallelism",
    "data parallelism",
    "batch inference",
    "async inference",
    "api inference",
    "model caching",
    "embedding cache",
    "vector indexing",
    "vector index",
    "faiss index",
    "ann index",
    "approximate nearest neighbor",
    "nearest neighbor search",
]

AI_APPLICATION_TERMS = [
    "resume screening",
    "cv screening",
    "resume parser",
    "cv parser",
    "candidate matching",
    "job matching",
    "recommendation engine",
    "document intelligence",
    "document processing",
    "document understanding",
    "intelligent search",
    "semantic matching",
    "semantic similarity",
    "text similarity",
    "question answering system",
    "knowledge assistant",
    "ai assistant",
    "virtual assistant",
    "customer support chatbot",
    "code assistant",
    "content generation",
    "content generation pipeline",
    "automated content generation",
    "personalization",
    "personalized recommendations",
]

CLASSICAL_ML_AI_CAP = 14

#ranking words

BACKEND_TERMS = ["fastapi", "django", "flask", "starlette", "sanic", "tornado", "aiohttp", "litestar", "falcon", "bottle", "async", "asyncio", "async programming", "asynchronous programming", "concurrency", "parallel processing", "multithreading", "multiprocessing", "postgresql", "postgres", "mysql", "mariadb", "sqlite", "mongodb", "mongo db", "redis", "sqlalchemy", "alembic", "prisma", "orm", "database", "database design", "database schema", "sql", "rest api", "restful api", "restful services", "api development", "api design", "backend development", "backend engineering", "server-side", "server side", "microservices", "microservice", "web services", "http", "https", "websocket", "websockets", "grpc", "graphql", "api gateway", "authentication", "authorization", "jwt", "oauth", "oauth2", "rbac", "middleware", "routing", "request handling", "background tasks", "background jobs", "task queue", "message queue"]

CLOUD_TERMS = ["gcp", "google cloud", "google cloud platform", "cloud run", "cloud functions", "cloud storage", "cloud sql", "firebase", "firestore", "aws", "amazon web services", "ec2", "ecs", "eks", "lambda", "s3", "rds", "dynamodb", "azure", "microsoft azure", "azure functions", "azure app service", "azure container apps", "docker", "dockerfile", "docker compose", "containerization", "containers", "kubernetes", "k8s", "helm", "terraform", "infrastructure as code", "iac", "ci/cd", "ci cd", "cicd", "continuous integration", "continuous deployment", "continuous delivery", "github actions", "gitlab ci", "jenkins", "circleci", "deployment", "deployed", "production deployment", "cloud deployment", "cloud infrastructure", "serverless", "serverless architecture", "load balancer", "auto scaling", "autoscaling", "scaling", "horizontal scaling", "vertical scaling", "cdn", "cloudflare", "nginx", "reverse proxy", "linux", "ubuntu"]

FULLSTACK_SUPPORT_TERMS = ["react", "reactjs", "react.js", "next.js", "nextjs", "next js", "javascript", "typescript", "html", "html5", "css", "css3", "tailwind", "tailwindcss", "bootstrap", "vite", "webpack", "node.js", "nodejs", "node js", "express", "express.js", "angular", "vue", "vue.js", "svelte", "frontend", "front-end", "frontend development", "full stack", "full-stack", "fullstack", "web application", "web development"]

ENGINEERING_DEPTH_TERMS = ["pytest", "unit test", "unit tests", "unit testing", "integration test", "integration tests", "integration testing", "end-to-end testing", "e2e testing", "test automation", "testing", "test-driven development", "tdd", "mocking", "fixtures", "caching", "cache", "redis cache", "cache invalidation", "distributed cache", "queue", "queues", "message queue", "task queue", "job queue", "celery", "rabbitmq", "kafka", "apache kafka", "observability", "logging", "structured logging", "monitoring", "metrics", "tracing", "distributed tracing", "opentelemetry", "prometheus", "grafana", "concurrency", "parallelism", "multithreading", "multiprocessing", "asyncio", "async programming", "retry", "retries", "retry logic", "exponential backoff", "backoff", "rate limit", "rate limiting", "throttling", "error handling", "exception handling", "fault tolerance", "resilience", "circuit breaker", "timeout", "timeouts", "graceful degradation", "architecture", "software architecture", "system architecture", "application architecture", "clean architecture", "layered architecture", "hexagonal architecture", "microservices architecture", "design patterns", "solid principles", "solid", "dependency injection", "modular design", "separation of concerns", "scalability", "high availability", "performance optimization", "optimization", "profiling", "load testing", "stress testing", "benchmarking", "api versioning", "schema validation", "input validation", "security", "secure coding", "secrets management", "environment variables", "configuration management", "code review", "code quality", "linting", "formatting", "pre-commit", "git hooks"]

MIN_TEXT_CHARS = 50

#settings
SECTION_ALIASES = {"summary": ["summary", "professional summary", "career summary", "professional profile", "profile", "career profile", "objective", "career objective", "professional objective", "career goals", "about me"], "skills": ["skills", "technical skills", "technical skill", "key skills", "core competencies", "core skills", "professional skills", "programming skills", "technical competencies", "skills & technologies", "technologies", "technical expertise", "areas of expertise", "expertise"], "experience": ["experience", "work experience", "professional experience", "relevant experience", "employment", "employment history", "work history", "career history", "professional history", "internship", "internships", "internship experience", "work experience and internships", "professional experience and internships"], "projects": ["projects", "key projects", "personal projects", "academic projects", "technical projects", "academic and personal projects", "personal and academic projects", "selected projects", "major projects", "project experience", "project work", "projects & experience"], "education": ["education", "academic background", "educational background", "academic qualifications", "educational qualifications", "qualifications", "academic history", "education background", "degrees", "academic details"], "achievements": ["achievements", "certifications", "certificates", "awards", "honors", "honours", "accomplishments", "achievements and awards", "certifications and awards", "awards and certifications", "professional certifications", "academic achievements"]}

NON_NAME_WORDS = {"resume", "curriculum", "vitae", "curriculum vitae", "cv", "summary", "objective", "objectives", "profile", "developer", "engineer", "engineering", "intern", "internship", "analyst", "designer", "consultant", "manager", "administrator", "architect", "scientist", "student", "graduate", "professional", "software", "technical", "data", "machine", "artificial", "intelligence", "full", "stack", "backend", "frontend", "specialist", "lead", "senior", "junior", "associate", "trainee", "candidate", "portfolio", "contact", "email", "phone", "address", "linkedin", "github"}

GITHUB_RESERVED_PATHS = {"features", "orgs", "organizations", "topics", "sponsors", "settings", "marketplace", "about", "pricing", "login", "logout", "explore", "search", "collections", "events", "enterprise", "team", "teams", "security", "customer-stories", "readme", "pulls", "issues", "notifications", "account", "dashboard", "new", "gist", "gists", "codespaces", "actions", "packages", "discussions", "releases", "wiki", "compare", "apps"}

#env

LLM_API_KEY = os.getenv("LLM_API_KEY", "")
LLM_MODEL = os.getenv("LLM_MODEL", "")



#eliginlity settings
WEAK_SECTIONS = {"skills", "summary", "achievements"}
IGNORED_SECTIONS = {"education"}      
AI_GENERIC_TERMS = ["llm"]             
ALLOW_CLASSICAL_ML_ELIGIBLE = True    
SKILL_VOCAB = [
    "Python", "Java", "JavaScript", "TypeScript", "C++", "SQL", "React",
    "Next.js", "Node.js", "Spring Boot", "FastAPI", "Django", "Flask",
    "PostgreSQL", "MongoDB", "MySQL", "Redis", "Docker", "Kubernetes",
    "GCP", "AWS", "Azure",
]

AI_DEPTH_MARKERS = [
    "retrieval", "tool", "orchestration", "state", "stateful", "evaluation",
    "pipeline", "workflow", "memory", "chunking", "reranking", "guardrails",
    "agent",
]

AI_WRAPPER_ONLY_TERMS = [
    "llm", "openai api", "gemini api", "claude api", "anthropic api",
]

TUTORIAL_HINTS = [
    "tutorial", "clone of", "following along", "udemy", "course project",
]

THIN_WRAPPER_PENALTY = 10
TUTORIAL_PENALTY = 5
NO_STRONG_AI_TOTAL_CAP = 50